// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQtTg_-W4owJWydSrshsseT1BQR6RKPiE',
    appId: '1:422166703812:web:016a7cda14491d2eafa391',
    messagingSenderId: '422166703812',
    projectId: 'mynotes-mgh',
    authDomain: 'mynotes-mgh.firebaseapp.com',
    storageBucket: 'mynotes-mgh.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-ZrgIelrD-534q-4iBXkuxxwbzQAHQSk',
    appId: '1:422166703812:android:9a352dbea2cfae3eafa391',
    messagingSenderId: '422166703812',
    projectId: 'mynotes-mgh',
    storageBucket: 'mynotes-mgh.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiDf39tlw_vNW8Gx2DK85L3nnd49-HNdg',
    appId: '1:422166703812:ios:d5fc5f0d8f81c3baafa391',
    messagingSenderId: '422166703812',
    projectId: 'mynotes-mgh',
    storageBucket: 'mynotes-mgh.appspot.com',
    iosBundleId: 'com.mgh.mynotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQtTg_-W4owJWydSrshsseT1BQR6RKPiE',
    appId: '1:422166703812:web:d1060a4a76633693afa391',
    messagingSenderId: '422166703812',
    projectId: 'mynotes-mgh',
    authDomain: 'mynotes-mgh.firebaseapp.com',
    storageBucket: 'mynotes-mgh.appspot.com',
  );
}
